"""Init

Revision ID: 88f2d9af65c5
Revises: 0eed7425c122
Create Date: 2024-04-24 11:29:37.922011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f2d9af65c5'
down_revision: Union[str, None] = '0eed7425c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_name', sa.String(length=50), nullable=False))
    op.drop_column('groups', 'name')
    op.add_column('students', sa.Column('student_name', sa.String(length=150), nullable=False))
    op.drop_column('students', 'fullname')
    op.add_column('subjects', sa.Column('subject', sa.String(length=175), nullable=False))
    op.drop_column('subjects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('name', sa.VARCHAR(length=175), autoincrement=False, nullable=False))
    op.drop_column('subjects', 'subject')
    op.add_column('students', sa.Column('fullname', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('students', 'student_name')
    op.add_column('groups', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('groups', 'group_name')
    # ### end Alembic commands ###
